### ISSUE TITLE
Notification email not sent

### ISSUE THREAD

**Issue by rdworth** [wycats/jquery-governance#74]
I created a motion and no email notification was received by anyone.

**Comment by thedelchop** [comment]
I believe I've corrected the issues with emails.  Please let me know if you've received emails in the last 24 hours about a motion called "Test motion to see if emails work".

**Comment by rdworth** [comment]
I got the emails. Thank you.

**Comment by thedelchop** [comment]
Ok, there we go.  Lets keep reporting issues here and I'll do my best to knock them down.
