### ISSUE TITLE
Url for motion is a little unintuitive

### ISSUE THREAD

**Issue by rdworth** [wycats/jquery-governance#78]
The url for a motion is http://jquery-voting.heroku.com/motions/8/events . Why /events at the end?

Also, it seems a bit odd that these two urls are errors
- http://jquery-voting.heroku.com/motions/8/
- http://jquery-voting.heroku.com/motions/8
  while these two urls work as expected:
- http://jquery-voting.heroku.com/motions/
- http://jquery-voting.heroku.com/motions

**Comment by gnandretta** [comment]
Fixed by 65bdbd9fab3b39baeb31b8ecff92c7a393642269.

Thanks!
